[settings]
pin = true
lockfile = true

[tools]
"npm:renovate" = { version = "44.38.0", trust_policy_excludes = ["@yarnpkg/libzip@3.2.2"] }

[tasks."renovate:check"]
description = "Validate renovate config files"
run = "renovate-config-validator renovate-config.json"
